amiaopensource/homebrew-amiaos

vrecord.rb

Will check if Pashua is installed via homebrew or if already is in the
applications folder.  If not found will attempt to install Pashua via
brew cask.

Add check for Pashua on install

---

vrecord.rb

Ran this through the homebrew style checker.

rubocop style

---

qcli.rb
qctools.rb

Related to https://github.com/bavc/qctools/issues/356

hotfix for the qctools hotfix

---

qcli.rb
qctools.rb

contingent on https://travis-ci.org/bavc/qctools/builds/222560791 which is rerunning now

0.8-1 is causing brew errors, reverting to 0.8

---

cable-bible.rb

once [pull request](https://github.com/amiaopensource/cable-bible/pull/23) to open cable-bible locally via CLI is approved, this formula will allow for install/update via homebrew and linuxbrew

add brew formula for cable-bible

---

ltopers.rb

- data-based versioning
- three levels of installation

update `ltopers` add `--with-db` and `--with-cuny`

---

ffmprovisr.rb

- preparing new release, please don’t merge
- SHA-256 needs to be updated

ffmprovisr v2017-07-15

---

ltopers.rb

- preparing new release, please don’t merge
- SHA-256 needs to be updated

LTOpers v2017-07-15

---

mkvparse.rb

- add version 1.1.0
- fix syntax
- resolves https://github.com/vi/mkvparse/issues/5

mkvparse version 1.1.0

---

qwt-qt5.rb

Should resolve https://github.com/amiaopensource/homebrew-amiaos/issues/60.

replace qt5 by qt

---

ltopers.rb

Waiting for https://github.com/amiaopensource/ltopers/pull/127.
Done.

new release of ltopers

---

pbprotracktor.rb

Please don’t merge yet! Waiting for https://github.com/amiaopensource/pbprotracktor/issues/16.
done

release 2017-09-23 of pbprotracktor

---

vrecord.rb

Waiting for https://github.com/amiaopensource/vrecord/pull/180.
done

vrecord v2017-09-26

---

decklinksdk.rb
ffmpegdecklink.rb

A WIP to build ffmpeg with decklink. I’m skeptical that homebrew will accept this approach, also I think it may be preferable to avoid conflict with the official homebrew ffmpeg formula, so this renames the output to ffmpeg-dl.

ffmpeg + decklink

---

ffmpegdecklink.rb

@dericed If I am not wrong, the ffmpeg 3.4 allows to simplify quite a lot.

ffmpegdecklink with ffmpeg 3.4

---

decklinksdk.rb

Possibly resolves https://github.com/amiaopensource/homebrew-amiaos/issues/67.

force version

---

vrecord.rb

should fix https://github.com/amiaopensource/vrecord/issues/208

use libopenjpeg as JPEG2000 encoder

---

ffmpegdecklink.rb

fixes https://github.com/amiaopensource/vrecord/issues/228

revision with SIGPIPE handling

---

ffmpegdecklink.rb

@dericed This could possibly be hold as WIP until the next release, in order to not forget. Any thoughts?

nit to make brew audit happy

---

ffmpegdecklink.rb

syncing with https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/74cf4a75f74ee3d80d021fc50b05e38bff5940e3?hp=04e4ab44d7c5eca9e1929b34d8fb966afc403e3a

update sigpipe patch

---

vrecord.rb

should resolve https://github.com/amiaopensource/vrecord/issues/252

add mediaconch dependency

---

vrecord.rb

- add `mkvtoolnix` dependency
- order dependencies alphabetically
- add a test
Should resolve https://github.com/amiaopensource/vrecord/issues/287.

vrecord version 2018-04-06

---

lenticular.rb

- add additional caveat
- add little information in man (instead of «to do»)
- uniform error messages

lenticular version 2018-05-26 alpha

---

ffmpegdecklink.rb

supersedes https://github.com/amiaopensource/homebrew-amiaos/pull/106

ffmpeg 4.0.1

---

ffmprovisr.rb

I guess, the switch to semantic tags justifies a new release.

ffmprovisr version 2018-07-29

---

vrecord.rb

and workaround for circular lua dependencies between lua and gnuplot

vrecord v2018-07-31

---

vrecord.rb

related to changes in https://github.com/amiaopensource/vrecord/pull/412

v2019-01-25

---

audiorecorder.rb

ffmpeg does not define option "with-freetype" anymore

freetype is now enabled in FFmpeg

---

decklinksdk.rb

Necessary for vrecord dependencies to be happy on linux

add system check

---

gtkdialog.rb

resolves https://github.com/amiaopensource/homebrew-amiaos/issues/173

gtkdialog: add libffi

---

audiorecorder.rb

2019-05-21 release

---

ffmprovisr.rb

ffmprovisr: 2019-07-19 release

---

vrecord.rb

could resolve https://github.com/amiaopensource/vrecord/issues/467 (untested)

vrecord: fix `mpv` dependency

---

ffmpegdecklink.rb

- fix the “Death Valley” issue, as done in the Homebrew formula
- add a comment to the previous fix

macOS 10.15 fix

---

mpv.rb

* New more current release
* Reflects transfer to AMIA-OS

transfer and release

---

mpv.rb

- caveats before test
- indentation
- double quote rather than single

mpv: make `brew audit --strict` happy

---

vrecord.rb

vrecord: make `brew audit --strict` happy

---

vrecord.rb

New release and addresses https://github.com/amiaopensource/homebrew-amiaos/issues/221

new release/update paths

---

dvrescue.rb

Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

Add formula for dvrescue

---

ffmpegdecklink.rb

sync with official Homebrew formula for FFmpeg

ffmpegdecklink clean-up

---

ffmpegdecklink.rb

patches based on @ThiloBorgmann's work
to be removed in the update to the version after 4.2.2

extend avfoundation.m patching prior to next ffmpeg release

---

dvrescue.rb

make `brew audit --strict` happy

---

TROUBLESHOOTING.md

should address https://github.com/amiaopensource/homebrew-amiaos/issues/213

troubles with mpv

---

ffmpegdecklink.rb

Reverts amiaopensource/homebrew-amiaos#241

Revert "ffmpegdecklink 4.2.3"

---

deckcontrol.rb
vrecord.rb

Testing is not yet complete, but I'm posting this as a work-in-progress to show a public alternative to https://github.com/amiaopensource/homebrew-amiaos/pull/247. Please do not approve or merge until WIP status is removed.

vrecord 2020-07-01

---

cable-bible.rb
ffmprovisr.rb
ltopers.rb
pbprotracktor.rb
vrecord.rb

- delete the `bottle :unneeded` directive, because it’s useless since some time

Housekeeping

---

vrecord.rb

Related to https://github.com/amiaopensource/vrecord/issues/577 & https://github.com/amiaopensource/homebrew-amiaos/issues/258.
@bturkus, @tomackroyd, please test.

mkvtoolnix only mojave or later

---

gtkdialog.rb

fixes https://github.com/amiaopensource/vrecord/issues/665, thx @bturkus

add additional gtkdialog build dependencies

---

gtkdialog.rb

This is happy on my end, but needs testing on the mac side of things!

gtkdialog: switch to new release

---

ffmpegdecklink.rb

Let's revert to ffmpeg 4.4 to resolve https://github.com/amiaopensource/vrecord/issues/722

Revert to ffmpeg 4.4

---

cable-bible.rb

make brew audit happy

---

ffmpegdecklink.rb

fixes https://github.com/amiaopensource/vrecord/issues/728

ffmpeg 5.1

---

TROUBLESHOOTING.md

Add fix for Ubuntu issues with ffmpegdecklink compilation

Add fix for ffmpegdecklink

---

TROUBLESHOOTING.md

This adds a tested work around for the issue reported in https://github.com/amiaopensource/vrecord/issues/735

Add gtkdialog fix (mac)

---

gtkdialog.rb

resolves https://github.com/amiaopensource/vrecord/issues/735

fixes for gtkdialog installs

---

TROUBLESHOOTING.md

Waiting for secondary confirmation of issue resolution, but got this ready

Update to add fontconfig issue

---

audioqc.rb

audioqc: 2023-11-22 release

---

ffmprovisr.rb

ffmprovisr 2025-04-16

---

README.md
audioqc.rb
decklinksdk.rb
digibase.rb
ffmprovisr.rb
grabbags.rb
gtkdialog.rb
ltopers.rb
mkvparse.rb
pbprotracktor.rb

infos in the individual commits

more housekeeping

---

ffmpegdecklink.rb

should work better with the new output strategy

update to ffmpeg 7.1.1

---

ffmpegdecklink.rb

fixes https://github.com/amiaopensource/vrecord/issues/904

fix drawtext in ffmpegdecklink

---

ffmprovisr.rb

- add trouble shooting
- delete get_recipe_list script

ffmprovisr 2025-09-30
