amiaopensource/homebrew-amiaos

ltopers.rb
I don't use ltopers but I follow the project. It looks like lto2filemaker was removed but this is not reflected in the brew recipe.
=> ltopers - remove lto2filemaker

vrecord.rb
I since ‘cask’ isn’t a dependency of vrecord, this seems like a safer way of doing this!
=> change cask install

ltopers.rb
is migratelto official? can it be added to the formula?
=> add `readlto` to ltopers.rb

ltopers.rb
Works on both Homebrew and Linuxbrew, when the `mm` formula is modified to `depends_on "dvdrtools" if OS.mac?` (see https://github.com/amiaopensource/homebrew-amiaos/issues/31).
=> ltopers v0.1.14

qctools.rb
this fixes --HEAD but a regular install will be broken until v0.8 is released, thus holding this til then
=> Qctools updates

ffmprovisr.rb
Partially addresses https://github.com/amiaopensource/ffmprovisr/issues/150
Downloads ffmprovisr to homebrew cellar and path installs script from https://github.com/amiaopensource/ffmprovisr/pull/181 to allow terminal shortcut
=> Ffmprovisr

cable-bible.rb
formula needs a release version that includes "cable-bible" shell script to install properly
=> update to v2017-05-08 release

qctools.rb
In my opinion:
- the `ENV["PATH"]` part is not used
- the `cd` commands can be simplified
I also have a doubt, that the `depends_on "freetype"` line is necessary, because there is already `depends_on "ffmpeg" => ["with-freetype"]`.
=> QCTools formula

vrecord.rb
Add `depends_on "freetype"` before `depends_on "ffmpeg" => ["with-sdl2", "with-freetype"]` in order to avoid an error message in _some_ situations.
=> add depends on freetype

audiorecorder.rb
I guess, we can now simplify. See https://github.com/Homebrew/homebrew-core/blob/master/Formula/bwfmetaedit.rb
=> add depends_on "bwfmetaedit"

ffmpegdecklink.rb
I've been getting some issues with having two ffmpeg library sets installed. I suggest that we use this formula as keg-only and direct scripts to use something like:
```
FFMPEG_DECKLINK=($(brew --prefix ffmpegdecklink)/bin/ffmpeg-dl)
FFPLAY_DECKLINK=($(brew --prefix ffmpegdecklink)/bin/ffplay-dl)
```
=> set to keg_only

ffmpegdecklink.rb
As has been done for the regular FFmpeg in https://github.com/Homebrew/homebrew-core/commit/894ef0a9ce8757b6746afa5035f11d916f87cb9f.
=> ffmpeg: update to 3.4.2 & avoid opportunistic linkage to jack

vrecord.rb
- The PR https://github.com/amiaopensource/vrecord/pull/324 must be merged before this one.
- A new built must be made (and, of course, `url`, `version` and `sha256` must be updated in this PR) before merging.
This gives to the user the possibility to choose if she or he wishes to install the `vtest` tool or not.
=> [WIP] add `--with-vtest` to `vrecord`

audiorecorder.rb
added option to install audiorecorder2 with tag `--with-audiorecorder2`
In Linux this will install to path and can be run via `audiorecorder2`
In macOS, audiorecorder2 will be built, and the containing folder is opened so that user can drag app to desired location.
Tested on my end for both systems and install was working!
=> Audiorecorder2

ffmpegdecklink.rb
The formula has been updated https://github.com/Homebrew/homebrew-core/commit/34351694168fc4c5589c6d75fffa0d6c87b1aa44
=> ffmpeg 4.0.2

audiorecorder.rb
Since FFmpeg version 4.0 or 4.1 (sorry, I don’t remember) the `--with-sdl2` option is set by default.
=> delete redundant option

bmdtools.rb
- alphabetical order
- version 0.2 is redundant with version scanned from URL
=> fix formula

ffmpegdecklink.rb
This PR includes (and therefore supersedes) https://github.com/amiaopensource/homebrew-amiaos/pull/165
- FFmpeg’s configure file enables by default `ffplay`, `lzma` and `pthreads`
- `avresample` is deprecated
=> update to FFmpeg 4.1.1 and housekeeping

ffmpegdecklink.rb
`--enable-nonfree` is always passed at [line 136](https://github.com/amiaopensource/homebrew-amiaos/blob/0c54269b8f656d3f326f94ec4271b24bd0aac890/ffmpegdecklink.rb#L136)
=> ffmpegdecklink: delete unneeded code

CODE_OF_CONDUCT.md, LICENSE, README.md
- add MIT License which should be retroactively approved by the contributors:
- add Contributor Covenant CoC
- update ReadMe:
- Linuxbrew has been merged into Homebrew
- add license
- add CoC
- add Copyright, Licence and Disclaimer
- add maintainer
=> Various updates

ffmpegdecklink.rb
- update to 4.1.4
- remove `--enable-hardcoded-tables`, because it’s not longer compatible with the 4.1 branch
=> ffmpeg 4.1.4

ffmpegdecklink.rb
- `brew [re]install ffmpegdecklink --with-iec61883` on macOS (10.13.6) gives:
`Error: invalid option: --with-iec61883`
- on Linux (Debian 9.9) works as wished
=> error message on macOS & add `decklinksdk` dependency

ffmpegdecklink.rb
- upgrade to FFmpeg 4.2.1
- move Python scripts out of `bin`
- add caveat about `mpv`
=> ffmpegdecklink: upgrade to FFmpeg 4.2.1

README.md, vrecord.rb
resolves https://github.com/amiaopensource/homebrew-amiaos/issues/209
Homebrew includes again an `mpv` formula. This considers `mpv 0.30.0` which is compatible with the current `ffmpeg`.
=> use Homebrew’s mpv

ffmpegdecklink.rb
- remove `texi2html`
- add `texinfo`
=> ffmpegdecklink: align to the canonical Homebrew formula

ffmpegdecklink.rb
see http://ffmpeg.org/pipermail/ffmpeg-devel/2020-November/271809.html
=> add patch based on Marton Balints fix for dv audio timestamps

decklinksdk.rb
- `Description shouldn't start with an article.`
=> make `brew audit --strict` happier

vrecord.rb
Bump, in order to make sure the last `ffmpegdecklink` is used. See https://github.com/amiaopensource/vrecord/issues/669.
=> vrecord: add revision

deckcontrol.rb
@privatezero please test via linuxbrew. As homebrew moved from /usr/local to /opt/homebrew the hardcoded include path for mac broke and this caused many vrecord installs to fail at this dependency (such as @bturkus at https://github.com/amiaopensource/vrecord/issues/673#issue-926477737). This update moves the BMSDK path to a Make variable so the homebrew installer can guess where it is rather than the Makefile.
=> deckcontrol v0.5

ffmpegdecklink.rb
- upgrade to FFmpeg 5.0
- enable neon support for H.265 on M1
- fix a file naming issue
=> ffmpegdecklink: upgrade to ffmpeg 5.0

vrecord.rb
To my knowledge the BAVC deckcontrol repository is not maintained to be cross-platform with linux (correct me if I'm wrong) so have moved this dependency.
Should resolve https://github.com/amiaopensource/vrecord/issues/731
=> deckcontrol to mac dependency

ffmpegdecklink.rb
based on suggestion from https://www.linuxquestions.org/questions/slackware-14/ffmpeg-compile-error-4175730203/
to fix https://github.com/amiaopensource/vrecord/issues/768#issuecomment-1795167778
=> disable htmlpages temporarily

vrecord.rb
- Version 2024-10-18 is redundant with version scanned from URL.
- Prefer `if MacOS.version >= :mojave` over `unless MacOS.version < :mojave`.
- Use `bin/"vrecord"` instead of `"#{bin}/vrecord"`.
=> vrecord: align to current preferred Homebrew syntax

vrecord.rb
Should fix brew error mentioned in https://github.com/amiaopensource/vrecord/issues/882
=> Fix typo of extra "
